language: node_js
node_js:
-14.16.1
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: "39.96.53.232"
branches:
  only:
  - master
install:
- npm install
before_script:
script:
- npm run build
after_script:
- pwd
- scp -o StrictHostKeyChecking=no -r dist/  root@39.96.53.232:/www/admin/www.chengru.top_80/wwwroot/